name: Commit Kustomizations
description: Commit all kustomization.yaml file changes in the k8s/ directory to the Default Branch
runs:
  using: composite
  steps:
    - run: make -Bf ${{ github.action_path }}/Makefile commit-kustomizations
      shell: bash
