name: Kustomize Image Tags
description: Set Kustomization Image Tags and Commit changes
inputs:
  images:
    description: Images to be pushed. Image tags will be used as suffix.
    required: false
  image-repos:
    description: Image Repositories
    required: false
    deprecationMessage: THIS INPUT IS DEPRECATED. Use 'images' instead.
  image-tag:
    description: Custom Image Tag
    required: false
    default: commit-sha
  path:
    description: Custom k8s path
    required: false
    default: ./k8s
runs:
  using: composite
  steps:
    - name: Enforce Manifests .yaml Extension
      shell: bash
      run: find ${{ inputs.path }}/overlays/*/kustomization.yml && echo 'This is an intentional error. K8s manifests extension must be ".yaml".' && exit 1 || echo 'Everything good to go!'
    - name: Set Kustomization Image Tags
      shell: bash
      run: |
        export IMAGE_TAG="$(make -Bsf ${{ github.action_path }}/Makefile IMAGE_TAG="${{ inputs.image-tag }}" image-tag)"
        export IMAGES="${{ inputs.images }}"
        export IMAGE_REPOS="${{ inputs.image-repos }}"
        if [[ ! -z "${IMAGES}" ]] && [[ ! -z "${IMAGE_REPOS}" ]]
        then
          echo '"images" and "image-repos" inputs are not allowed simultaneously. "image-repos" is deprecated. Use "images" instead'
        elif [[ -z "${IMAGES}" ]]
        then
          export IMAGES="${IMAGE_REPOS}"
        fi
        export K8S_PATH="${{ inputs.path }}"

        make -Bf ${{ github.action_path }}/Makefile OVERLAY="global-product" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="integration" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="production" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="staging" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile commit-kustomizations
