name: Set Kustomization Images
description: Set Kustomization Images and Commit changes
inputs:
  production:
    description: Prodution Environment Images
    required: false
  staging:
    description: Staging Environment Images
    required: false
  integration:
    description: Integration Environment Images
    required: false
runs:
  using: composite
  steps:
    - name: Export Tag
      run: echo TAG="$(git describe --always --dirty --exclude '*')" >> "${GITHUB_ENV}"
      shell: bash
    - name: Set Kustomization Images
      run: |
        export IMAGES="${{ inputs.production }}"
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="production" edit-kustomizations
        export IMAGES="${{ inputs.staging }}"
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="staging" edit-kustomizations
        export IMAGES="${{ inputs.staging }}"
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="integration" edit-kustomizations
      shell: bash
    - name: Commit Kustomizations
      run: make -Bf ${{ github.action_path }}/Makefile commit-kustomizations
      shell: bash
