name: Kustomize Image Tags
description: Set Kustomization Image Tags and Commit changes
inputs:
  images:
    description: K8s Images
    required: false
runs:
  using: composite
  steps:
    - name: Export Tag
      run: echo TAG="$(git describe --always --dirty --exclude '*')" >> "${GITHUB_ENV}"
      shell: bash
    - name: Set Kustomization Image Tags
      run: |
        export IMAGES="${{ inputs.images }}"
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="integration" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="production" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="staging" edit-kustomizations
      shell: bash
    - name: Commit Kustomizations
      run: make -Bf ${{ github.action_path }}/Makefile commit-kustomizations
      shell: bash
