name: Kustomize Image Tags
description: Set Kustomization Image Tags and Commit changes
inputs:
  image-repos:
    description: Image Repositories
    required: true
runs:
  using: composite
  steps:
    - name: Set Kustomization Image Tags
      run: |
        export IMAGE_REPOS="${{ inputs.image-repos }}"
        export IMAGE_TAG="$(make -Bsf ${{ github.action_path }}/Makefile image-tag)"
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="integration" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="production" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile OVERLAY="staging" edit-kustomizations
        make -Bf ${{ github.action_path }}/Makefile commit-kustomizations
      shell: bash
